# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ListDir < Formula
  desc "Listar recursivamente archivos y directorios"
  homepage "https://github.com/drossan/list-dir-go"
  version "0.0.2"
  depends_on :macos

  url "https://github.com/drossan/list-dir-go/releases/download/v0.0.2/list-dir-go_0.0.2_darwin_all.tar.gz"
  sha256 "a608c7ddfec91665d761d6f2a2b8f5e0f0e3f309457fa318cdc391e4d9d737ae"

  def install
    bin.install "server-cx"
  end
end
