# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ListDir < Formula
  desc "Listar recursivamente archivos y directorios"
  homepage "https://github.com/drossan/list-dir-go"
  version "0.0.3"
  depends_on :macos

  url "https://github.com/drossan/list-dir-go/releases/download/v0.0.3/list-dir-go_0.0.3_darwin_all.tar.gz"
  sha256 "9dac06f1a4297e34849530113143c68a374442ce8011edbdc922ea225877b332"

  def install
    bin.install "list-dir"
  end
end
