# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerCx < Formula
  desc "Listar recursivamente archivos y directorios"
  homepage "https://github.com/drossan/list-dir-go"
  version "0.0.1"
  depends_on :macos

  url "https://github.com/drossan/list-dir-go/releases/download/v0.0.1/list-dir-go_0.0.1_darwin_all.tar.gz"
  sha256 "1c72fb141749f21ce1d492e64bceb356f9039707770ed3f8b57dab0541ce1b5c"

  def install
    bin.install "server-cx"
  end
end
